### ISSUE TITLE
Restart needed after adding a new page

### ISSUE THREAD

**Issue by natasha-moore-elastic** [elastic/docs-builder-example#10]
The readme says that all changes should be reflected on the live site without restarting, but when adding a new file, the serve container in Docker needs to be restarted for the page to show up.

Also, a `title` in the frontmatter is needed for the page to show up, but there’s no error to indicate this if you don’t provide one.

**Comment by Mpdreamz** [comment]
This PR should hopefully address the need to restart!

https://github.com/elastic/docs-builder/pull/90 

It will also fallback to the relative path of the file if no title is provided.

**Comment by Mpdreamz** [comment]
Warnings for no title in front matter (or level header 1) are now also emitted as part of

https://github.com/elastic/docs-builder/pull/91

NOTE: I am working on surfacing these errors in the HTML so you do not need to scan the docker logs for them.

**Comment by Mpdreamz** [comment]
Hey @natasha-moore-elastic 

You can update your docker container to reflect the latest changes:


```sh
docker pull ghcr.io/elastic/docs-builder:edge
```

Every commit on `main` in that repository gets pushed there and tagged with `edge`. 

I should **really** document this 😸

**Comment by Mpdreamz** [comment]
@natasha-moore-elastic @bmorelli25 just pointed out that `serve` was not working so I made some changes.


Can you pull the latest docker image again as well as the latest changes from main on this repository?
