### ISSUE TITLE
Substitutions within code blocks

### ISSUE THREAD

**Issue by lcawl** [elastic/docs-builder-example#6]
I was playing with some content copied from https://www.elastic.co/guide/en/elasticsearch/reference/current/targz.html in https://github.com/elastic/docs-builder-example/pull/4 
I noticed that with the following source content:

````
The Linux archive for {{es}} v{{version}} can be downloaded and installed as follows:

```{code} sh
wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-{{version}}-linux-x86_64.tar.gz
wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-{{version}}-linux-x86_64.tar.gz.sha512
shasum -a 512 -c elasticsearch-{{version}}-linux-x86_64.tar.gz.sha512 <1>
tar -xzf elasticsearch-{{version}}-linux-x86_64.tar.gz
cd elasticsearch-{{version}}/ <2>
```
...
````

The "{{es}}" and "{{version}}" work in the paragraph but not within the code block:

![Image](https://github.com/user-attachments/assets/27ae408b-dfc3-44f9-8417-1b47ec9c3b32)

If this is not supported in the proposed doc system, we'll need to find an alternative way to allow users to cut and paste this type of variable command.

**Comment by Mpdreamz** [comment]
Thanks for finding this @lcawl substitutions should work "everywhere" as they are parsed and part of the AST. 

Codeblock rendering is special and follows a customized routine currently that was not aware of these leafs in the AST. 


https://github.com/elastic/docs-builder/pull/92 should fix this.
