### ISSUE TITLE
Version errors

### ISSUE THREAD

**Issue by lcawl** [elastic/docs-builder-example#9]
https://github.com/elastic/docs-builder-example/pull/8 is generating the following errors:

```
Error: 3.7 is not a valid version
   ┌─[/github/workspace/docs/source/elastic/deploy/ece/ubuntu3.md]
   │
 5 │ ```{versionadded} 3.7
   · ────────────────     
   ·                       
   │
   └─
 
Error: 3.3 is not a valid version
   ┌─[/github/workspace/docs/source/elastic/deploy/ece/ubuntu2.md]
   │
 5 │ ```{versionadded} 3.3
   · ────────────────     
   ```                       
   
This is because the page I created was for Elastic Cloud Enterprise, which has non-Stack versioning (unless it's complaining because I omitted the "m" in V.R.M?).
This is part of a bigger discussion about how we handle versioning in the new docs system, but I think for now we probably want either (a) no version-related errors or (b) an exhaustive list of all the varied types of versions that we cover in our docs (not for the faint of heart).

**Comment by Mpdreamz** [comment]
>  (unless it's complaining because I omitted the "m" in V.R.M?) 

It is, it currently expects a full semantic version. I can definitely relax this.

**Comment by Mpdreamz** [comment]
Fixed in https://github.com/elastic/docs-builder/pull/89
